version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile  # Adjust this if your Dockerfile is inside a subfolder
    container_name: flask-container
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - prometheus
    networks:
      - monitoring
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring
    restart: unless-stopped

networks:
  monitoring:
    driver: bridge
