apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 8080  # Kubernetes will expose your app on this port
